apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traffic-gen
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Fastasix/diiage-finals.git
    targetRevision: HEAD
    path: traffic-gen-app/chart
  destination:
    server: https://kubernetes.default.svc
    namespace: traffic
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
