apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: traffic-egress-only-backend
spec:
  podSelector: {}
  policyTypes:
    - Egress
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: backend
      ports:
        - protocol: TCP
          port: 80
